#!/bin/bash
# enable_linux_telemetry.sh
# 
# Configures minimum viable telemetry for EDR Linux deployment.
# Run as root or with sudo.
#
# This script:
# - Configures auditd with rules for process, file, network, and privesc monitoring
# - Ensures journald retains enough history
# - Validates prerequisites
#
# Usage: sudo ./enable_linux_telemetry.sh [--dry-run]

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

DRY_RUN=false
if [[ "${1:-}" == "--dry-run" ]]; then
    DRY_RUN=true
    echo -e "${YELLOW}[DRY-RUN MODE] No changes will be made${NC}"
fi

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check root
if [[ $EUID -ne 0 ]] && [[ "$DRY_RUN" == false ]]; then
    log_error "This script must be run as root"
    exit 1
fi

# ============================================================================
# Prerequisites Check
# ============================================================================

log_info "Checking prerequisites..."

# Check kernel version (need 5.8+ for full eBPF support, 4.x works for auditd)
KERNEL_VERSION=$(uname -r | cut -d. -f1-2)
KERNEL_MAJOR=$(echo "$KERNEL_VERSION" | cut -d. -f1)
KERNEL_MINOR=$(echo "$KERNEL_VERSION" | cut -d. -f2)

if [[ "$KERNEL_MAJOR" -lt 4 ]]; then
    log_error "Kernel $KERNEL_VERSION is too old. Minimum supported: 4.18"
    exit 1
elif [[ "$KERNEL_MAJOR" -eq 4 ]] && [[ "$KERNEL_MINOR" -lt 18 ]]; then
    log_error "Kernel $KERNEL_VERSION is too old. Minimum supported: 4.18"
    exit 1
elif [[ "$KERNEL_MAJOR" -lt 5 ]] || [[ "$KERNEL_MAJOR" -eq 5 && "$KERNEL_MINOR" -lt 8 ]]; then
    log_warn "Kernel $KERNEL_VERSION detected. eBPF support may be limited."
    log_warn "Consider upgrading to 5.8+ for full feature support."
else
    log_info "Kernel $KERNEL_VERSION - Full eBPF support available"
fi

# Check for auditd
if ! command -v auditctl &> /dev/null; then
    log_warn "auditctl not found. Installing auditd..."
    if [[ "$DRY_RUN" == false ]]; then
        if command -v apt-get &> /dev/null; then
            apt-get update && apt-get install -y auditd audispd-plugins
        elif command -v dnf &> /dev/null; then
            dnf install -y audit
        elif command -v yum &> /dev/null; then
            yum install -y audit
        else
            log_error "Could not install auditd. Please install manually."
            exit 1
        fi
    fi
fi

# Check for journald
if ! command -v journalctl &> /dev/null; then
    log_error "journalctl not found. systemd-journald is required."
    exit 1
fi

log_info "Prerequisites OK"

# ============================================================================
# Audit Rules Configuration
# ============================================================================

AUDIT_RULES_FILE="/etc/audit/rules.d/edr-linux.rules"
AUDIT_RULES_CONTENT='# EDR Linux Telemetry Rules
# Generated by enable_linux_telemetry.sh
# Do not edit manually - rerun script to update

# Remove any existing rules (clean slate)
-D

# Set buffer size (increase for high-volume systems)
-b 8192

# Failure mode: 1 = printk, 2 = panic
-f 1

# ============================================================================
# Process Execution Monitoring
# ============================================================================

# 64-bit execve
-a always,exit -F arch=b64 -S execve -F key=exec

# 32-bit execve (for compatibility)
-a always,exit -F arch=b32 -S execve -F key=exec

# execveat (newer syscall)
-a always,exit -F arch=b64 -S execveat -F key=exec

# ============================================================================
# Credential File Access
# ============================================================================

# Shadow file access (credential theft indicator)
-a always,exit -F arch=b64 -S open,openat -F path=/etc/shadow -F perm=r -F key=shadow_read
-a always,exit -F arch=b64 -S open,openat -F path=/etc/gshadow -F perm=r -F key=shadow_read

# SSH key access
-a always,exit -F arch=b64 -S open,openat -F dir=/root/.ssh -F perm=r -F key=ssh_keys
-a always,exit -F arch=b64 -S open,openat -F dir=/home -F path=*.ssh/id_* -F perm=r -F key=ssh_keys

# ============================================================================
# Network Monitoring
# ============================================================================

# Outbound connections
-a always,exit -F arch=b64 -S connect -F key=network_connect

# Inbound connections (server mode)
-a always,exit -F arch=b64 -S accept,accept4 -F key=network_accept

# Socket creation
-a always,exit -F arch=b64 -S socket -F a0=2 -F key=network_socket  # AF_INET
-a always,exit -F arch=b64 -S socket -F a0=10 -F key=network_socket # AF_INET6

# ============================================================================
# Persistence Mechanisms
# ============================================================================

# Cron modifications
-a always,exit -F arch=b64 -S open,openat,creat -F dir=/etc/cron.d -F perm=wa -F key=cron_persist
-a always,exit -F arch=b64 -S open,openat,creat -F dir=/etc/cron.daily -F perm=wa -F key=cron_persist
-a always,exit -F arch=b64 -S open,openat,creat -F dir=/etc/cron.hourly -F perm=wa -F key=cron_persist
-a always,exit -F arch=b64 -S open,openat,creat -F dir=/etc/cron.weekly -F perm=wa -F key=cron_persist
-a always,exit -F arch=b64 -S open,openat,creat -F dir=/etc/cron.monthly -F perm=wa -F key=cron_persist
-a always,exit -F arch=b64 -S open,openat,creat -F path=/etc/crontab -F perm=wa -F key=cron_persist
-a always,exit -F arch=b64 -S open,openat,creat -F dir=/var/spool/cron -F perm=wa -F key=cron_persist

# Systemd service persistence
-a always,exit -F arch=b64 -S open,openat,creat -F dir=/etc/systemd/system -F perm=wa -F key=systemd_persist
-a always,exit -F arch=b64 -S open,openat,creat -F dir=/usr/lib/systemd/system -F perm=wa -F key=systemd_persist

# Init script persistence
-a always,exit -F arch=b64 -S open,openat,creat -F dir=/etc/init.d -F perm=wa -F key=init_persist
-a always,exit -F arch=b64 -S open,openat,creat -F path=/etc/rc.local -F perm=wa -F key=init_persist

# SSH authorized_keys (backdoor indicator)
-a always,exit -F arch=b64 -S open,openat,creat -F path=/root/.ssh/authorized_keys -F perm=wa -F key=ssh_persist

# Shell profile persistence
-a always,exit -F arch=b64 -S open,openat,creat -F path=/etc/profile -F perm=wa -F key=shell_persist
-a always,exit -F arch=b64 -S open,openat,creat -F dir=/etc/profile.d -F perm=wa -F key=shell_persist
-a always,exit -F arch=b64 -S open,openat,creat -F path=/etc/bashrc -F perm=wa -F key=shell_persist
-a always,exit -F arch=b64 -S open,openat,creat -F path=/etc/bash.bashrc -F perm=wa -F key=shell_persist

# ============================================================================
# Privilege Escalation
# ============================================================================

# UID/GID changes
-a always,exit -F arch=b64 -S setuid,setgid,setreuid,setregid -F key=privesc_uid
-a always,exit -F arch=b64 -S setresuid,setresgid -F key=privesc_uid

# Capability changes
-a always,exit -F arch=b64 -S capset -F key=privesc_caps

# Sudo configuration
-a always,exit -F arch=b64 -S open,openat,creat -F path=/etc/sudoers -F perm=wa -F key=sudo_config
-a always,exit -F arch=b64 -S open,openat,creat -F dir=/etc/sudoers.d -F perm=wa -F key=sudo_config

# ============================================================================
# Kernel Module Loading
# ============================================================================

-a always,exit -F arch=b64 -S init_module,finit_module -F key=kernel_module
-a always,exit -F arch=b64 -S delete_module -F key=kernel_module

# ============================================================================
# Process Injection / Debug
# ============================================================================

-a always,exit -F arch=b64 -S ptrace -F key=ptrace_debug
-a always,exit -F arch=b64 -S process_vm_readv,process_vm_writev -F key=process_vm

# ============================================================================
# Anti-Forensics / Log Tampering
# ============================================================================

# Log file deletion
-a always,exit -F arch=b64 -S unlink,unlinkat -F dir=/var/log -F key=log_delete
-a always,exit -F arch=b64 -S rename,renameat -F dir=/var/log -F key=log_tamper

# History file tampering
-a always,exit -F arch=b64 -S unlink,unlinkat -F path=/root/.bash_history -F key=history_tamper

# ============================================================================
# Memory Protection Changes (shellcode / exploit indicators)
# ============================================================================

-a always,exit -F arch=b64 -S mprotect -F a2&0x4 -F key=mem_protect_exec
-a always,exit -F arch=b64 -S memfd_create -F key=memfd

# Make rules immutable (requires reboot to change)
# Uncomment for production hardening:
# -e 2
'

log_info "Configuring audit rules..."

if [[ "$DRY_RUN" == true ]]; then
    echo "Would write to: $AUDIT_RULES_FILE"
    echo "---"
    echo "$AUDIT_RULES_CONTENT" | head -50
    echo "... (truncated)"
else
    echo "$AUDIT_RULES_CONTENT" > "$AUDIT_RULES_FILE"
    chmod 640 "$AUDIT_RULES_FILE"
    log_info "Wrote audit rules to $AUDIT_RULES_FILE"
fi

# ============================================================================
# Journald Configuration
# ============================================================================

JOURNALD_CONF="/etc/systemd/journald.conf.d/edr-retention.conf"

log_info "Configuring journald retention..."

if [[ "$DRY_RUN" == false ]]; then
    mkdir -p /etc/systemd/journald.conf.d
    cat > "$JOURNALD_CONF" << 'EOF'
# EDR Linux - Journald Retention Configuration
# Ensure enough history for incident investigation

[Journal]
# Store on disk (not just RAM)
Storage=persistent

# Keep at least 7 days of logs
MaxRetentionSec=7day

# Cap total size at 2GB
SystemMaxUse=2G

# Keep at least 500MB free
SystemKeepFree=500M

# Individual file max size
SystemMaxFileSize=100M

# Compress older journals
Compress=yes
EOF
    chmod 644 "$JOURNALD_CONF"
    log_info "Wrote journald config to $JOURNALD_CONF"
else
    echo "Would create: $JOURNALD_CONF"
fi

# ============================================================================
# Apply Configuration
# ============================================================================

if [[ "$DRY_RUN" == false ]]; then
    log_info "Applying audit rules..."
    
    # Restart auditd to load new rules
    if systemctl is-active --quiet auditd; then
        # auditd doesn't like systemctl restart, use service command
        service auditd restart || systemctl restart auditd
    else
        systemctl start auditd
        systemctl enable auditd
    fi
    
    # Verify rules loaded
    RULE_COUNT=$(auditctl -l 2>/dev/null | grep -c "key=" || echo "0")
    log_info "Loaded $RULE_COUNT audit rules"
    
    log_info "Restarting journald..."
    systemctl restart systemd-journald
    
    log_info "Configuration applied successfully!"
else
    echo ""
    echo "To apply changes, run without --dry-run:"
    echo "  sudo $0"
fi

# ============================================================================
# Verification
# ============================================================================

echo ""
log_info "=== Verification ==="

echo ""
echo "Audit daemon status:"
if systemctl is-active --quiet auditd; then
    echo -e "  ${GREEN}●${NC} auditd is running"
else
    echo -e "  ${RED}●${NC} auditd is NOT running"
fi

echo ""
echo "Sample audit rules (exec monitoring):"
auditctl -l 2>/dev/null | grep "key=exec" | head -3 || echo "  (no exec rules found)"

echo ""
echo "Journald storage:"
journalctl --disk-usage 2>/dev/null || echo "  (could not query)"

echo ""
echo "Recent exec events (last 5):"
ausearch -k exec -ts recent 2>/dev/null | head -20 || echo "  (no recent events or ausearch not available)"

# ============================================================================
# Summary
# ============================================================================

echo ""
echo "============================================================================"
log_info "EDR Linux Telemetry Configuration Complete"
echo "============================================================================"
echo ""
echo "Telemetry sources enabled:"
echo "  ✓ Process execution (execve/execveat)"
echo "  ✓ Network connections (connect/accept)"
echo "  ✓ Credential file access (/etc/shadow, SSH keys)"
echo "  ✓ Persistence mechanisms (cron, systemd, init)"
echo "  ✓ Privilege escalation (setuid, capabilities)"
echo "  ✓ Kernel module loading"
echo "  ✓ Process injection (ptrace)"
echo "  ✓ Anti-forensics detection"
echo ""
echo "Files created/modified:"
echo "  - $AUDIT_RULES_FILE"
echo "  - $JOURNALD_CONF"
echo ""
echo "Next steps:"
echo "  1. Verify telemetry with: ausearch -k exec -ts recent"
echo "  2. Start EDR locald: edr-locald --config /etc/edr/locald.toml"
echo "  3. Monitor: journalctl -u edr-locald -f"
echo ""

if [[ "$DRY_RUN" == true ]]; then
    log_warn "This was a DRY RUN - no changes were made"
fi
